name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - '*'

permissions:
  contents: write
  packages: write
  actions: read

jobs:
  verify_backend_quality:
    name: Verify Backend Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install Dependencies
        run: go mod tidy

      - name: Run go vet
        run: go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.61.0
          working-directory: ./
          only-new-issues: false
          args: --concurrency=16 --timeout=5m --out-format=github-actions --issues-exit-code=1 --verbose
          skip-cache: false
          skip-pkg-cache: true

  verify_backend_functionality:
    name: Verify Backend Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: go tests
        run: go test ./... -v

  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs:
      - verify_backend_quality
      - verify_backend_functionality

    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Build
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/email-scraper-${{ matrix.goos }}-${{ matrix.goarch }} main.go

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: email-scraper-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/email-scraper-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: email-scraper-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}